version: '3.8'

services:
  app:
    image: trieu81200111/team-28-backend
    volumes:
      - ./public/images:/app/public/images
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb-team-28
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: