version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-team-28
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: